#define CONSOLE_UART_CHANNEL (0)

#define HEAD_UART_CHANNEL (1)
#define TAIL_UART_CHANNEL (2)

#define HEAD_UART_RX_PIN
#define HEAD_UART_RX_PIN

#define DEFAULT_UART_CHANNEL (0)
#define CONSOLE_UART_CHANNEL (1 - DEFAULT_UART_CHANNEL)
#define DEFAULT_UART_RX_PIN (3)
#define DEFAULT_UART_TX_PIN (2)
#define CONSOLE_UART_RX_PIN (4)
#define CONSOLE_UART_TX_PIN (5)

#define UARTS_BAUD_RATE (115200)
#define TASK_STACK_SIZE (2048)
#define READ_BUF_SIZE (1024)
