#define CONSOLE_UART_CHANNEL (0)
#define PROBE1_UART_CHANNEL (1)
#define PROBE2_UART_CHANNEL (2)

#define CONSOLE_UART_RX_PIN (3)
#define CONSOLE_UART_TX_PIN (1)
#define PROBE1_UART_RX_PIN (34)
#define PROBE1_UART_TX_PIN (32)
#define PROBE2_UART_RX_PIN (35)
#define PROBE2_UART_TX_PIN (33)

#define UARTS_BAUD_RATE (115200)
#define TASK_STACK_SIZE (2048)
#define READ_BUF_SIZE (1024)
